### ISSUE TITLE
Everytime you open a feedback comment, the app scrolls back to the top.

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#1]
| Description  |
| ------------- | 
| The app scrolls up everytime you open a feedback|
|<ul><li>server:https://dev.psi-mis.org/</li><li>User: android, Password: Fork.2020</li></ul>|

| How to replicate |
| ------------- | 
|<ul><li>Open RDQA Program v2</li><li>Open Feedback tab</li><li>Open malaria and Pneumonia sections</li><li>In Pneumonia, open any question to see the feedback</li></ul>|

| Screenshot/Video |
| ------------- | 
|![20201012153247](https://user-images.githubusercontent.com/44774809/95792208-35b09e00-0ca0-11eb-851f-b77497510347.gif)|

**Comment by ifoche** [comment]
Hi @nancyespinoza. We will be reviewing it on Friday the latest on Monday. Our scheduled time to address all what can still be addressed with the time that last from this month maintenance is next Monday.

**Comment by nancyespinoza** [comment]
This keeps happening in 2.3.1 Fork
