### ISSUE TITLE
sharing feedback

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-capture-app-psi-fork#10]

**Comment by nancyespinoza** [comment]
![image](https://user-images.githubusercontent.com/44774809/109592743-61a8b080-7ad5-11eb-8f54-b0dc20b58749.png)

Is this link supposed to work now?

![image](https://user-images.githubusercontent.com/44774809/109592815-86048d00-7ad5-11eb-85ec-3435d9e17410.png)

**Comment by nancyespinoza** [comment]
After a discussion with Rodolfo, the following message should be display when sharing the feedback:

![image](https://user-images.githubusercontent.com/44774809/109867892-a430d100-7c2c-11eb-891e-c0116b3e3554.png)
