### ISSUE TITLE
Error with 'Assign' Program rules

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#11]
The 2.3.1 Fork is not applying any of the assign rules for HNQI/RDQA programs. 

## How to replicate
Test against 2.3.1 android capture app (https://github.com/dhis2/dhis2-android-capture-app/releases/tag/2.3.1) with the user android (password Fork.2020). 
1. Open any TEI in the HNQIS Program 
2. Open the Assessment stage
3. Go to the Critical steps calculations or Scores and you'll see all the values are being assigned correctly
4. Now with the same credentials and the 2.3.1 FORK repeat the steps and you'll see the values are not being assigned.

You can also test this with RDQA Program

**Comment by ifoche** [comment]
only the first 2 or 3 questions already should produce a score, or even without data there are some assign rules (organisation unit: should appear with the ou code & health area: should be assigning the program UID)

**Comment by ifoche** [comment]
Hi @nancyespinoza . Sorry but we're still unable to reproduce it. I've forwarded you an email with a new apk and the steps we're following, together with a screenshot with this working (here also attached). Could you please let me know after testing with that particular situation to check that it's still not working in that case for you?
![Screenshot_20210407-113853](https://user-images.githubusercontent.com/10931645/113846854-303b9880-9797-11eb-9d4b-8301b107f533.png)

**Comment by nancyespinoza** [comment]
Everything is working as expected with the new [apk](https://drive.google.com/file/d/1lHTvbBNcevsQVMfKWs1Hlgv8DTaic9Yp/view?usp=sharing
). 

Thank you

**Comment by nancyespinoza** [comment]
Hi @ifoche! I was able to see the program rules working in the previous apk and with 2.3.2 I cannot longer see them working

![PR error](https://user-images.githubusercontent.com/44774809/114493309-90876b80-9bd7-11eb-8199-8ba9a216bc8d.gif)

**Comment by ifoche** [comment]
Hi @nancyespinoza. Looks like the error comes from the compilation of the app. I was apparently pointing to a wrong commit in the rules-engine repository, and that created all this problem. I'm really sorry. Will regenerate a new apk and send it to you asap
