### ISSUE TITLE
The text does not show fully when opening more than two feedback boxes at the time

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#13]
![FeedbackText](https://user-images.githubusercontent.com/44774809/114494447-a85fef00-9bd9-11eb-959a-d4e58085b3ee.gif)

**Comment by ifoche** [comment]
@nancyespinoza we have not been able to reproduce the problem in multiple devices... could you maybe let us know which device you're using? Especially the screen size might be important
