### ISSUE TITLE
Sharing feedback Message

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#14]
Current URL in message: https://feedback.psi-mis.org/[server]/[enrollmentID]

New URL in message: https://client-dev.psi-connect.org/hnqis_rdqa//assessment.html?id=[enrollmentID]&server=[serverURL]

Example: https://client-dev.psi-connect.org/hnqis_rdqa//assessment.html?id=K6R5nVdOanW&server=https://dev.psi-mis.org

**Comment by ifoche** [comment]
Notes from meeting:
- During the debug period use the URL above, but on production
- Definitive UID: https://client.psi-connect.org/hnqis_rdqa//assessment.html?id=[enrollmentID]&server=[serverURL]&lang=[lang]
