### ISSUE TITLE
PR error in 2.33.5 server (possible bug?)

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#19]
Hi Ignacio!

There is a server in which the hide field rules are not working. I think that the problem is with the server and not with the app but could you please confirm this?

Credentials:
Server: https://dev.imdatahub.org
User: hnqis.test 
Password: Solar123!

Steps to follow:
1. Log in
2. In the "XX IM HNQIS2 - HF Readiness" program create or open any Assessment
3. Create an Assessment stage
4. In section 2 "General information" Select "No" to the question "Add another Staff?"

The expected behavior is that all the remaining questions in the section should hide.

**Comment by ifoche** [comment]
@nancyespinoza we've checked it and it seems that there are issues with the configuration of some PRs. Concretely there are errors with program rule conditions, where program rule variables of calculated value type have not value, e.g:
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS10}*100)/100: Infinity or NaN: NaN
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS3}*100)/100: Infinity or NaN: NaN
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS5}*100)/100: Infinity or NaN: NaN
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS6}*100)/100: Infinity or NaN: NaN
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS8}*100)/100: Infinity or NaN: NaN
- E/RuleEngineExecution: Unexpected exception while evaluating d2:round(#{CV_CS9}*100)/100: Infinity or NaN: NaN

Program rule variables CV_CS10,CV_CS3,CV_CS5,CV_CS6,CV_CS8,CV_CS9 seem not to have a value, so the condition fail to divide 0/100 or nan/100. 

We think these conditions in the program rule actions should be changed to verify previously if the variable has value before executing the division operation, or the failure may be before that. Could you please confirm that it helps to identify the configuration error?
