### ISSUE TITLE
[2.5.2] Feedback displays empty DEs

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#28]
**To Reproduce**
Credentials
Server: https://236dev.psi-mis.org
User: hnqis2.fork
Password: Solar123!

1. Go to HNQIS2 Fork Testing Program
2. Make a new enrollmetn
3. Add an Assessment stage
4. Save the stage and open the feedback
5. DEs "Section A: Critical" and "Section B: Hidden Section" are shown
6. Sync the enrollment
7. Go back to the feedback - they are not shown

**Expected behavior**
<img width="159" alt="image" src="https://user-images.githubusercontent.com/44774809/165344454-5f837496-21aa-462a-9f9b-2097542e2102.png">

**Current behavior**
<img width="162" alt="image" src="https://user-images.githubusercontent.com/44774809/165345619-77d88dc0-526e-47ee-8ef8-2fdc0c99adfb.png">

**Comment by ifoche** [comment]
Hi @nancyespinoza . After reviewing this, we think that it may not be an error, depending on the reasons to have that specific configuration. 

Those DEs have a feedback order set up. If you don't want them in the feedback, is it really needed? Could you just remove the feedback order so they are not shown in the feedback screen?

In case that is needed, then what is happening is that DHIS2 official app sync is removing the null values from the DB. That is why first time you can see it (as it has a feedback order and an null value) and then the sync removes the value so it disappears from the feedback. Our proposal in this case would be to:
- We could remove from the feedback list any DE for whom the value is empty and/or null
- We could investigate how to make the form to avoid creating null values (this would be a modification of the DHIS2 official app so would imply probably a PR and so on). Maybe this solution would be faster if you create a Jira ticket to the Android team?

Is there any of the options you like more? Do you prefer to wait for our meeting to discuss it?

**Comment by ifoche** [comment]
We will remove any empty/null value DE from the feedback
