### ISSUE TITLE
Incorrect order in "by technical area" tab

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#3]
| Credentials  |
| ------------- | 
|<ul><li>server:https://dev.psi-mis.org/</li><li>User: android, Password: Fork.2020</li></ul>|

| How to replicate |
| ------------- | 
|<ul><li>Open RDQA Program</li><li>Open Feedback tab</li><li>Compare the two tabs, the indicator tab shows the correct order.</li></ul>|

| Doc |
| ------------- | 
|![Order](https://user-images.githubusercontent.com/44774809/95809873-019fa200-0ccd-11eb-9719-46a5ad312ebe.png)|

**Comment by ifoche** [comment]
Hi @nancyespinoza. We will be reviewing it on Friday the latest on Monday. Our scheduled time to address all what can still be addressed with the time that last from this month maintenance is next Monday.
