### ISSUE TITLE
How does the app classifies critical and no critical in the feedback tab?

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#5]
![image](https://user-images.githubusercontent.com/44774809/98014282-0c77bf00-1dc1-11eb-84e5-62dd3890a8a1.png)

**Comment by ifoche** [comment]
Hi @nancyespinoza . The app right now looks at the mandatory field. In case a data element is mandatory it will be considered critical. However, as we need to represent all the tree above a certain question, if a critical question is children of a non-critical one, we have to also render the non-critical one, even if we're in the critical tab
