### ISSUE TITLE
Hyperlinks for feedback text don't open

### ISSUE THREAD

**Issue by nancyespinoza** [EyeSeeTea/dhis2-android-capture-app-psi-fork#7]
Difficulty to open hyperlinks. Sometimes, you have to click multiple times before the app opens the URL.

**Comment by ifoche** [comment]
Hi @nancyespinoza. We will be reviewing it on Friday the latest on Monday. Our scheduled time to address all what can still be addressed with the time that last from this month maintenance is next Monday.
